### PR TITLE
learn to code

### PR DESCRIPTION
**Pull request by MineGW**
holy shit your code is a mess

### CODE REVIEW

**Comment by MineGW** [comment]
i actually cant bring myself to fixing the bot from how much of a clusterfuck it is how the hell do you accomplish that

**Comment by XxGamerBroskixX** [comment]
Sup teebs or whoever the fuck it is.
You barely made the code even any better.
Don't come here unless you're either gay or jealous.
@MineGW

**Comment by MineGW** [comment]
i cant make the code any better because your code is absolute shit,
why would i need to be jealous about a github nuke?
seriously please make like a journalist and learn to code

**Comment by MineGW** [comment]
also i heard one of your friends got kiked trying to use your bot lmfao

**Comment by HandsomeMadMario** [comment]
fucking retard lmao

**Comment by MineGW** [comment]
also thanks for putting it on github so we can all laugh at your shit code with ease

**Pull request closed without merging**
